<?php


class students extends person
{
public $group;
public function __construct($name, $age, $address, $group)
{
    parent::__construct($name, $age, $address);
    $this->group = $group;
}
public function getInfo()
{
    return parent::getInfo() . ' group:' . $this->group; // TODO: Change the autogenerated stub
}

}